#pragma once

typedef enum
{
	TRANSFORM_ZOOMALL,
	TRANSFORM_ZOOMEXTENTS,
	TRANSFORM_ZOOMIN,
	TRANSFORM_ZOOMOUT,
	TRANSFORM_ZOOMREALTIME,
	TRANSFORM_ZOOMCENTER,
	TRANSFORM_ROTATELEFT,
	TRANSFORM_ROTATERIGHT
}TransformActions;